//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.WebApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_product()
        {
            this.transaction = new HashSet<transaction>();
        }
    
        public int id { get; set; }
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public decimal balance { get; set; }
        public string status { get; set; }
        public string product_number { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transaction { get; set; }
    }
}
