//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.WebApi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mybankEntities2 : DbContext
    {
        public mybankEntities2()
            : base("name=mybankEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_product> customer_product { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<transaction> transaction { get; set; }
        public virtual DbSet<transaction_type> transaction_type { get; set; }
    }
}
