//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capgemini.WebApi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int customer_product_id { get; set; }
        public int channel_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public int type { get; set; }
        public int transaction_number { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual customer_product customer_product { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
